--- #YAML:1.0
name:                Math-Complex
version:             1.56
abstract:            ~
license:             perl
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Scalar::Util:                  1.11
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
