# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Complex
version:      1.48
version_from: lib/Math/Complex.pm
installdirs:  perl
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
